config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "welcome#index"

  resources :users, only: [:new, :create]

  get "/login", to: "users#login_form"
  post "/login", to: "users#login"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord 
  validates :username, uniqueness: true, presence: true 
  validates_presence_of :password

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  def new 
    @user = User.new
  end

  def create 
    user = user_params 
    user[:username] = user[:username].downcase
    new_user = User.create(user)
    session[:user_id] = new_user.id
    flash[:success] = "Welcome, #{new_user.username}!"
    redirect_to root_path
  end

  def login_form 

  end

  def login 
    user = User.find_by(username: params[:username])
    if user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome, #{user.username}!"
      redirect_to root_path
    else 
      flash[:error] = "Sorry, your credentials are bad."
      render :login_form
    end
  end

  private 
  def user_params 
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController 
  def index 
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthenticationPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/login_form.html.erb
<%= form_with url: login_path, method: :post do |form| %>
  <%= form.label :username, "Username:" %> 
  <%= form.text_field :username %>

  <%= form.label :password, "Password" %>
  <%= form.text_field :password %>

  <%= form.submit "Log In" %>
<% end %>

app/views/users/new.html.erb
<%= form_with model: @user do |form| %>
  <%= form.label :username, "Username:" %>
  <%= form.text_field :username %>

  <%= form.label :password, "Password:" %>
  <%= form.password_field :password %>

  <%= form.submit "Create User"%>

<% end %>

app/views/welcome/index.html.erb
<%if current_user %>
  <%= link_to "Log Out" %>
<% else %>
  <%= link_to "Register as User", new_user_path %>
  <%= link_to "I already have an account", login_path%>
<% end %>